SORTING A STRUCTURE
WE DON'T NEED TO OVERLOAD < OPERATOR WE CAN JUST PASS COMP FUNCTION 
SORT(V.BEGIN(),V.END(),MYCOMP)

BUT FOR PRIORITY_QUEUE WE CAN'T PASS A FUNCTION WE NEED TO OVERLOAD < OPERATOR
